# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# MongoDB
spring.data.mongodb.uri=mongodb+srv://vulps_admin:Wt74Khij1pSAhcxN@vulpsfashion-cluster.ngzjj7y.mongodb.net/vulpsfashiondb?appName=vulpsfashion-cluster

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Logging
logging.level.org.apache.catalina.util.SessionIdGeneratorBase=ERROR

# Cloudinary
cloudinary.cloud-name=doofeu0ki
cloudinary.api-key=771333599241998
cloudinary.api-secret=y9TzvfxbVZLo02riZ0VAtukwSwY
